version: '3.3'
services:
  faktory:
    image: contribsys/faktory
    environment:
      - FAKTORY_PASSWORD=increase
    ports:
      - 7419:7419
      - 7420:7420
    networks:
      - default
    volumes:
      - faktory-data:/var/lib/faktory

  worker:
    build: .
    environment:
      - FAKTORY_URL=tcp://:increase@faktory:7419
      - WORKER=TRUE
    networks:
      - default

  api:
    build: .
    environment:
      - FAKTORY_URL=tcp://:increase@faktory:7419
      - WORKER=FALSE
    ports:
      - 8080:8080
    networks:
      - default

networks:
  default:
volumes:
  faktory-data:
